version: '3'
services:
  app:
    build: .
    environment:
      - SVELTE_URL_WITH_SLASH=https://deployfirstwebsite-tofly-production.up.railway.app/
    ports:
      - "80:80"
      - "4696:4696"
    command: /app/entrypoint.sh
    # networks:
    #   default:
    #     driver: bridge
