version: '3'
services:
  app:
    build: .
    environment:
      - SVELTE_URL_WITH_SLASH=https://first-website-backend-900694380542.asia-south1.run.app/
    ports:
      - "5173:5173"
      - "4696:4696"
    command: /app/entrypoint.sh
    # networks:
    #   default:
    #     driver: bridge
