# fly.toml app configuration file generated for generate-website on 2024-06-05T17:03:49+05:30
# 
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "generate-website"
primary_region = "cdg"

[build]

[env]
 SVELTE_URL_WITH_SLASH='https://generate-website.fly.dev/'

[[services]]
internal_port = 5173
protocol = "tcp"
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20
[[services.ports]]
handlers = ["http"]
port = 80
[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services]]
internal_port = 4696
protocol = "tcp"
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20
[[services.ports]]
handlers = ["http"]
port = 4696
[[services.ports]]
handlers = ["tls", "http"]
port = 4697

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
